logging:
  level:
    org.springframework.web: ERROR
    com.thestick: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:9000/TheStick
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver